on:
  push:
  workflow_dispatch:
  workflow_call:
    outputs:
      image-tag:
        description: "image tag"
        value: ${{ jobs.build-and-test.outputs.image-tag }}

name: ci

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # need this for OIDC
      contents: read
    environment: ${{ github.ref_name }}
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}         

      # Add steps here like linting, testing, minification, etc.
      - name: Cfn Lint
        id: cfn-lint
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        id: cfn-lint-run
        run: |
          shopt -s globstar # enable globbing
          cfn-lint --version
          cfn-lint -t ./templates/*.yaml

      - name: Cfn Nag
        id: cfn-nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: templates
          #output_path: cfn_nag.sarif

      # - uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: cfn_nag.sarif

      # Build images
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to AWS ECR
        id: build-image
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}          
        run: |
          echo "Building image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          cd app
          docker build \
              -t $ECR_REPOSITORY:latest \
              -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
              -t $ECR_REPOSITORY:$IMAGE_TAG \
              -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG          
          echo "Pushed image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Set image tag output
        id: set-image-tag
        env:
          IMAGE_TAG: ${{ github.sha }}        
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT